// Our own method for invitations people send themselves (#47), beside the
// mls.* ones and for the same reason: a file of its own that regenerating
// upstream's schema cannot drop. The wire encoding towards the phone is
// written by hand in invite.go; this exists because the services inside the
// server talk protobuf to each other.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: invite.proto

package mtproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RPCInvite_InviteMint_FullMethodName = "/mtproto.RPCInvite/invite_mint"
)

// RPCInviteClient is the client API for RPCInvite service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RPCInviteClient interface {
	InviteMint(ctx context.Context, in *TLInviteMint, opts ...grpc.CallOption) (*Invite_Minted, error)
}

type rPCInviteClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCInviteClient(cc grpc.ClientConnInterface) RPCInviteClient {
	return &rPCInviteClient{cc}
}

func (c *rPCInviteClient) InviteMint(ctx context.Context, in *TLInviteMint, opts ...grpc.CallOption) (*Invite_Minted, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Invite_Minted)
	err := c.cc.Invoke(ctx, RPCInvite_InviteMint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCInviteServer is the server API for RPCInvite service.
// All implementations should embed UnimplementedRPCInviteServer
// for forward compatibility.
type RPCInviteServer interface {
	InviteMint(context.Context, *TLInviteMint) (*Invite_Minted, error)
}

// UnimplementedRPCInviteServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRPCInviteServer struct{}

func (UnimplementedRPCInviteServer) InviteMint(context.Context, *TLInviteMint) (*Invite_Minted, error) {
	return nil, status.Error(codes.Unimplemented, "method InviteMint not implemented")
}
func (UnimplementedRPCInviteServer) testEmbeddedByValue() {}

// UnsafeRPCInviteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCInviteServer will
// result in compilation errors.
type UnsafeRPCInviteServer interface {
	mustEmbedUnimplementedRPCInviteServer()
}

func RegisterRPCInviteServer(s grpc.ServiceRegistrar, srv RPCInviteServer) {
	// If the following call panics, it indicates UnimplementedRPCInviteServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RPCInvite_ServiceDesc, srv)
}

func _RPCInvite_InviteMint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLInviteMint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCInviteServer).InviteMint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCInvite_InviteMint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCInviteServer).InviteMint(ctx, req.(*TLInviteMint))
	}
	return interceptor(ctx, in, info, handler)
}

// RPCInvite_ServiceDesc is the grpc.ServiceDesc for RPCInvite service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPCInvite_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mtproto.RPCInvite",
	HandlerType: (*RPCInviteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "invite_mint",
			Handler:    _RPCInvite_InviteMint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "invite.proto",
}
