// Our own method for invitations people send themselves (#47), beside the
// mls.* ones and for the same reason: a file of its own that regenerating
// upstream's schema cannot drop. The wire encoding towards the phone is
// written by hand in invite.go; this exists because the services inside the
// server talk protobuf to each other.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: invite.proto

package mtproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// invite.mint phone:string = invite.Minted;
//
// Mints a code bound to this number for the person asking, who vouches for
// whoever holds it. The phone's own SMS app carries the code; the server never
// sends anything.
type TLInviteMint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLInviteMint) Reset() {
	*x = TLInviteMint{}
	mi := &file_invite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLInviteMint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLInviteMint) ProtoMessage() {}

func (x *TLInviteMint) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLInviteMint.ProtoReflect.Descriptor instead.
func (*TLInviteMint) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{0}
}

func (x *TLInviteMint) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

// invite.minted code:string expires:int = invite.Minted;
//
// expires is Unix seconds: the moment the code stops working.
type Invite_Minted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Expires       int32                  `protobuf:"varint,2,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invite_Minted) Reset() {
	*x = Invite_Minted{}
	mi := &file_invite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invite_Minted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invite_Minted) ProtoMessage() {}

func (x *Invite_Minted) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invite_Minted.ProtoReflect.Descriptor instead.
func (*Invite_Minted) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{1}
}

func (x *Invite_Minted) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Invite_Minted) GetExpires() int32 {
	if x != nil {
		return x.Expires
	}
	return 0
}

var File_invite_proto protoreflect.FileDescriptor

const file_invite_proto_rawDesc = "" +
	"\n" +
	"\finvite.proto\x12\amtproto\"&\n" +
	"\x0eTL_invite_mint\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"=\n" +
	"\rinvite_Minted\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\aexpires\x18\x02 \x01(\x05R\aexpires2M\n" +
	"\tRPCInvite\x12@\n" +
	"\vinvite_mint\x12\x17.mtproto.TL_invite_mint\x1a\x16.mtproto.invite_Minted\"\x00B#Z!github.com/teamgram/proto/mtprotob\x06proto3"

var (
	file_invite_proto_rawDescOnce sync.Once
	file_invite_proto_rawDescData []byte
)

func file_invite_proto_rawDescGZIP() []byte {
	file_invite_proto_rawDescOnce.Do(func() {
		file_invite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_invite_proto_rawDesc), len(file_invite_proto_rawDesc)))
	})
	return file_invite_proto_rawDescData
}

var file_invite_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_invite_proto_goTypes = []any{
	(*TLInviteMint)(nil),  // 0: mtproto.TL_invite_mint
	(*Invite_Minted)(nil), // 1: mtproto.invite_Minted
}
var file_invite_proto_depIdxs = []int32{
	0, // 0: mtproto.RPCInvite.invite_mint:input_type -> mtproto.TL_invite_mint
	1, // 1: mtproto.RPCInvite.invite_mint:output_type -> mtproto.invite_Minted
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_invite_proto_init() }
func file_invite_proto_init() {
	if File_invite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_invite_proto_rawDesc), len(file_invite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_invite_proto_goTypes,
		DependencyIndexes: file_invite_proto_depIdxs,
		MessageInfos:      file_invite_proto_msgTypes,
	}.Build()
	File_invite_proto = out.File
	file_invite_proto_goTypes = nil
	file_invite_proto_depIdxs = nil
}
