// Our own methods, for end-to-end encryption on MLS (2bytes #36).
//
// Kept in a file of its own rather than added to the generated schema, so that
// regenerating that schema from upstream cannot quietly drop them, and so that
// updating this module has exactly one file to carry across.
//
// The wire encoding these types use towards the phone is written by hand in
// mls.go - MTProto, not protobuf. This file exists because the services inside
// the server talk protobuf to each other, and a type that is not a protobuf
// message cannot make that hop.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: mtproto/mls.proto

package mtproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A device leaving a supply of key packages, so that somebody can start a
// conversation with it while it is asleep.
type TLMlsPublishKeyPackages struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	KeyPackages [][]byte               `protobuf:"bytes,1,rep,name=key_packages,json=keyPackages,proto3" json:"key_packages,omitempty"`
	// May be empty. When it is not, it is the one package handed out repeatedly
	// once the supply runs dry - the weaker path, taken so that a conversation
	// can still start.
	LastResort []byte `protobuf:"bytes,2,opt,name=last_resort,json=lastResort,proto3" json:"last_resort,omitempty"`
	// The leaf name of the identity these belong to.
	//
	// A device that starts its state over makes a new identity, and the packages
	// it published under the old one stay here. The server counts a device's
	// supply by its auth key, so it sees a full one, never asks for more, and
	// everybody who starts a conversation with that person builds an invitation
	// the person can never open (#136).
	Name          []byte `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMlsPublishKeyPackages) Reset() {
	*x = TLMlsPublishKeyPackages{}
	mi := &file_mtproto_mls_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMlsPublishKeyPackages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMlsPublishKeyPackages) ProtoMessage() {}

func (x *TLMlsPublishKeyPackages) ProtoReflect() protoreflect.Message {
	mi := &file_mtproto_mls_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMlsPublishKeyPackages.ProtoReflect.Descriptor instead.
func (*TLMlsPublishKeyPackages) Descriptor() ([]byte, []int) {
	return file_mtproto_mls_proto_rawDescGZIP(), []int{0}
}

func (x *TLMlsPublishKeyPackages) GetKeyPackages() [][]byte {
	if x != nil {
		return x.KeyPackages
	}
	return nil
}

func (x *TLMlsPublishKeyPackages) GetLastResort() []byte {
	if x != nil {
		return x.LastResort
	}
	return nil
}

func (x *TLMlsPublishKeyPackages) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

// What was taken, and whether the device should make more. The decision to
// refill stays with the only party that can make packages.
type Mls_PublishResult struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Added        int32                  `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	Available    int32                  `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	ShouldRefill bool                   `protobuf:"varint,3,opt,name=should_refill,json=shouldRefill,proto3" json:"should_refill,omitempty"`
	// How many devices of this account have published anything. It is what tells
	// a phone that another phone of the same person has signed in since a
	// conversation started (#41).
	Devices       int32 `protobuf:"varint,4,opt,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mls_PublishResult) Reset() {
	*x = Mls_PublishResult{}
	mi := &file_mtproto_mls_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mls_PublishResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mls_PublishResult) ProtoMessage() {}

func (x *Mls_PublishResult) ProtoReflect() protoreflect.Message {
	mi := &file_mtproto_mls_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mls_PublishResult.ProtoReflect.Descriptor instead.
func (*Mls_PublishResult) Descriptor() ([]byte, []int) {
	return file_mtproto_mls_proto_rawDescGZIP(), []int{1}
}

func (x *Mls_PublishResult) GetAdded() int32 {
	if x != nil {
		return x.Added
	}
	return 0
}

func (x *Mls_PublishResult) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *Mls_PublishResult) GetShouldRefill() bool {
	if x != nil {
		return x.ShouldRefill
	}
	return false
}

func (x *Mls_PublishResult) GetDevices() int32 {
	if x != nil {
		return x.Devices
	}
	return 0
}

// Asks for one package per device of a person, which is what starting a
// conversation with them needs: each device is a member of its own.
type TLMlsClaimKeyPackages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMlsClaimKeyPackages) Reset() {
	*x = TLMlsClaimKeyPackages{}
	mi := &file_mtproto_mls_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMlsClaimKeyPackages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMlsClaimKeyPackages) ProtoMessage() {}

func (x *TLMlsClaimKeyPackages) ProtoReflect() protoreflect.Message {
	mi := &file_mtproto_mls_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMlsClaimKeyPackages.ProtoReflect.Descriptor instead.
func (*TLMlsClaimKeyPackages) Descriptor() ([]byte, []int) {
	return file_mtproto_mls_proto_rawDescGZIP(), []int{2}
}

func (x *TLMlsClaimKeyPackages) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// One package per device that had something. A device with nothing left is
// missing from here rather than failing the request - one silent device must
// not stop a conversation with the rest.
type Mls_KeyPackages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Packages      [][]byte               `protobuf:"bytes,1,rep,name=packages,proto3" json:"packages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mls_KeyPackages) Reset() {
	*x = Mls_KeyPackages{}
	mi := &file_mtproto_mls_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mls_KeyPackages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mls_KeyPackages) ProtoMessage() {}

func (x *Mls_KeyPackages) ProtoReflect() protoreflect.Message {
	mi := &file_mtproto_mls_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mls_KeyPackages.ProtoReflect.Descriptor instead.
func (*Mls_KeyPackages) Descriptor() ([]byte, []int) {
	return file_mtproto_mls_proto_rawDescGZIP(), []int{3}
}

func (x *Mls_KeyPackages) GetPackages() [][]byte {
	if x != nil {
		return x.Packages
	}
	return nil
}

// A welcome is what lets a device into a conversation somebody started with it.
//
// It travels here rather than as a message, so that no client has to hide
// anything from a chat list: handshake traffic never touches the message
// pipeline at all. The server holds each one until the device says it has read
// it - a welcome lost in transit is a conversation that exists on one side and
// not the other, which shows up much later as messages that will not open.
type TLMlsSendWelcome struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	UserId  int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Welcome []byte                 `protobuf:"bytes,2,opt,name=welcome,proto3" json:"welcome,omitempty"`
	// Which chat the invitation is for, as a dialog id - negative for a group,
	// positive for a person. A dialog id and not either client's internal packed
	// form: the two clients pack them differently, and one reading the other's
	// packing crashed on the path every invitation takes.
	// Without it a welcome says only who sent it, and the device joining files
	// the conversation under that person: a group ends up recorded as the
	// conversation with whoever invited them, and a private message to that
	// person is then written with the group's keys (#115).
	PeerId        int64 `protobuf:"varint,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMlsSendWelcome) Reset() {
	*x = TLMlsSendWelcome{}
	mi := &file_mtproto_mls_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMlsSendWelcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMlsSendWelcome) ProtoMessage() {}

func (x *TLMlsSendWelcome) ProtoReflect() protoreflect.Message {
	mi := &file_mtproto_mls_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMlsSendWelcome.ProtoReflect.Descriptor instead.
func (*TLMlsSendWelcome) Descriptor() ([]byte, []int) {
	return file_mtproto_mls_proto_rawDescGZIP(), []int{4}
}

func (x *TLMlsSendWelcome) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TLMlsSendWelcome) GetWelcome() []byte {
	if x != nil {
		return x.Welcome
	}
	return nil
}

func (x *TLMlsSendWelcome) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

type TLMlsGetWelcomes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMlsGetWelcomes) Reset() {
	*x = TLMlsGetWelcomes{}
	mi := &file_mtproto_mls_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMlsGetWelcomes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMlsGetWelcomes) ProtoMessage() {}

func (x *TLMlsGetWelcomes) ProtoReflect() protoreflect.Message {
	mi := &file_mtproto_mls_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMlsGetWelcomes.ProtoReflect.Descriptor instead.
func (*TLMlsGetWelcomes) Descriptor() ([]byte, []int) {
	return file_mtproto_mls_proto_rawDescGZIP(), []int{5}
}

// Ours rather than the schema's Bool, so this file needs nothing from the
// generated schema and survives its regeneration untouched.
type Mls_Ok struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mls_Ok) Reset() {
	*x = Mls_Ok{}
	mi := &file_mtproto_mls_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mls_Ok) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mls_Ok) ProtoMessage() {}

func (x *Mls_Ok) ProtoReflect() protoreflect.Message {
	mi := &file_mtproto_mls_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mls_Ok.ProtoReflect.Descriptor instead.
func (*Mls_Ok) Descriptor() ([]byte, []int) {
	return file_mtproto_mls_proto_rawDescGZIP(), []int{6}
}

func (x *Mls_Ok) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type Mls_Welcome struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromId  int64                  `protobuf:"varint,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	Welcome []byte                 `protobuf:"bytes,3,opt,name=welcome,proto3" json:"welcome,omitempty"`
	// The chat this invitation is for. Zero for one written before invitations
	// carried it, and then the old guess - the sender - is all there is.
	PeerId        int64 `protobuf:"varint,4,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mls_Welcome) Reset() {
	*x = Mls_Welcome{}
	mi := &file_mtproto_mls_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mls_Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mls_Welcome) ProtoMessage() {}

func (x *Mls_Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_mtproto_mls_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mls_Welcome.ProtoReflect.Descriptor instead.
func (*Mls_Welcome) Descriptor() ([]byte, []int) {
	return file_mtproto_mls_proto_rawDescGZIP(), []int{7}
}

func (x *Mls_Welcome) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Mls_Welcome) GetFromId() int64 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *Mls_Welcome) GetWelcome() []byte {
	if x != nil {
		return x.Welcome
	}
	return nil
}

func (x *Mls_Welcome) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

type Mls_Welcomes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Welcomes      []*Mls_Welcome         `protobuf:"bytes,1,rep,name=welcomes,proto3" json:"welcomes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mls_Welcomes) Reset() {
	*x = Mls_Welcomes{}
	mi := &file_mtproto_mls_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mls_Welcomes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mls_Welcomes) ProtoMessage() {}

func (x *Mls_Welcomes) ProtoReflect() protoreflect.Message {
	mi := &file_mtproto_mls_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mls_Welcomes.ProtoReflect.Descriptor instead.
func (*Mls_Welcomes) Descriptor() ([]byte, []int) {
	return file_mtproto_mls_proto_rawDescGZIP(), []int{8}
}

func (x *Mls_Welcomes) GetWelcomes() []*Mls_Welcome {
	if x != nil {
		return x.Welcomes
	}
	return nil
}

// Read is not the same as delivered. A device confirms only after the
// conversation is open and saved, so a crash in between costs a retry rather
// than the conversation.
type TLMlsConfirmWelcomes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMlsConfirmWelcomes) Reset() {
	*x = TLMlsConfirmWelcomes{}
	mi := &file_mtproto_mls_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMlsConfirmWelcomes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMlsConfirmWelcomes) ProtoMessage() {}

func (x *TLMlsConfirmWelcomes) ProtoReflect() protoreflect.Message {
	mi := &file_mtproto_mls_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMlsConfirmWelcomes.ProtoReflect.Descriptor instead.
func (*TLMlsConfirmWelcomes) Descriptor() ([]byte, []int) {
	return file_mtproto_mls_proto_rawDescGZIP(), []int{9}
}

func (x *TLMlsConfirmWelcomes) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

// A commit is what moves a conversation from one epoch to the next: somebody
// added, somebody removed. MLS validates it against the epoch it was made from,
// so of two commits made from the same epoch exactly one can be taken - the
// server keeps that order, which RFC 9420 gives to the delivery service.
//
// The members are named because the server does not know who is in a group and
// must not: it is told where to leave the commit, not asked who belongs.
type TLMlsSendCommit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       []byte                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Epoch         int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Members       []int64                `protobuf:"varint,3,rep,packed,name=members,proto3" json:"members,omitempty"`
	Commit        []byte                 `protobuf:"bytes,4,opt,name=commit,proto3" json:"commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMlsSendCommit) Reset() {
	*x = TLMlsSendCommit{}
	mi := &file_mtproto_mls_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMlsSendCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMlsSendCommit) ProtoMessage() {}

func (x *TLMlsSendCommit) ProtoReflect() protoreflect.Message {
	mi := &file_mtproto_mls_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMlsSendCommit.ProtoReflect.Descriptor instead.
func (*TLMlsSendCommit) Descriptor() ([]byte, []int) {
	return file_mtproto_mls_proto_rawDescGZIP(), []int{10}
}

func (x *TLMlsSendCommit) GetGroupId() []byte {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *TLMlsSendCommit) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *TLMlsSendCommit) GetMembers() []int64 {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *TLMlsSendCommit) GetCommit() []byte {
	if x != nil {
		return x.Commit
	}
	return nil
}

// Whether the commit was taken, and which epoch the conversation is really on.
//
// The epoch comes back on refusal as well, so the loser of a race knows how far
// behind it is without another round trip - it has to catch up, rebuild its
// change on top of the winner and send again.
type Mls_CommitResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Epoch         int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mls_CommitResult) Reset() {
	*x = Mls_CommitResult{}
	mi := &file_mtproto_mls_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mls_CommitResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mls_CommitResult) ProtoMessage() {}

func (x *Mls_CommitResult) ProtoReflect() protoreflect.Message {
	mi := &file_mtproto_mls_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mls_CommitResult.ProtoReflect.Descriptor instead.
func (*Mls_CommitResult) Descriptor() ([]byte, []int) {
	return file_mtproto_mls_proto_rawDescGZIP(), []int{11}
}

func (x *Mls_CommitResult) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *Mls_CommitResult) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type TLMlsGetCommits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMlsGetCommits) Reset() {
	*x = TLMlsGetCommits{}
	mi := &file_mtproto_mls_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMlsGetCommits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMlsGetCommits) ProtoMessage() {}

func (x *TLMlsGetCommits) ProtoReflect() protoreflect.Message {
	mi := &file_mtproto_mls_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMlsGetCommits.ProtoReflect.Descriptor instead.
func (*TLMlsGetCommits) Descriptor() ([]byte, []int) {
	return file_mtproto_mls_proto_rawDescGZIP(), []int{12}
}

type Mls_Commit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromId        int64                  `protobuf:"varint,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	GroupId       []byte                 `protobuf:"bytes,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Epoch         int64                  `protobuf:"varint,4,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Commit        []byte                 `protobuf:"bytes,5,opt,name=commit,proto3" json:"commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mls_Commit) Reset() {
	*x = Mls_Commit{}
	mi := &file_mtproto_mls_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mls_Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mls_Commit) ProtoMessage() {}

func (x *Mls_Commit) ProtoReflect() protoreflect.Message {
	mi := &file_mtproto_mls_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mls_Commit.ProtoReflect.Descriptor instead.
func (*Mls_Commit) Descriptor() ([]byte, []int) {
	return file_mtproto_mls_proto_rawDescGZIP(), []int{13}
}

func (x *Mls_Commit) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Mls_Commit) GetFromId() int64 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *Mls_Commit) GetGroupId() []byte {
	if x != nil {
		return x.GroupId
	}
	return nil
}

func (x *Mls_Commit) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Mls_Commit) GetCommit() []byte {
	if x != nil {
		return x.Commit
	}
	return nil
}

type Mls_Commits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commits       []*Mls_Commit          `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mls_Commits) Reset() {
	*x = Mls_Commits{}
	mi := &file_mtproto_mls_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mls_Commits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mls_Commits) ProtoMessage() {}

func (x *Mls_Commits) ProtoReflect() protoreflect.Message {
	mi := &file_mtproto_mls_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mls_Commits.ProtoReflect.Descriptor instead.
func (*Mls_Commits) Descriptor() ([]byte, []int) {
	return file_mtproto_mls_proto_rawDescGZIP(), []int{14}
}

func (x *Mls_Commits) GetCommits() []*Mls_Commit {
	if x != nil {
		return x.Commits
	}
	return nil
}

// Applied, not received. A device that took a commit and stopped before saving
// the state it produced must be given it again, or it sits an epoch behind and
// the conversation goes quiet for that person alone.
type TLMlsConfirmCommits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMlsConfirmCommits) Reset() {
	*x = TLMlsConfirmCommits{}
	mi := &file_mtproto_mls_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMlsConfirmCommits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMlsConfirmCommits) ProtoMessage() {}

func (x *TLMlsConfirmCommits) ProtoReflect() protoreflect.Message {
	mi := &file_mtproto_mls_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMlsConfirmCommits.ProtoReflect.Descriptor instead.
func (*TLMlsConfirmCommits) Descriptor() ([]byte, []int) {
	return file_mtproto_mls_proto_rawDescGZIP(), []int{15}
}

func (x *TLMlsConfirmCommits) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

// How many devices each of these people has published from.
//
// Everything that compares a conversation with its chat reads the part of a
// leaf name before the slash, so it reasons about people. That is wrong the
// moment somebody replaces a phone: the leaf of the device that is gone still
// stands for them, nobody counts them as missing, and the phone they now hold
// is never let in - they sit in the chat watching padlocks for ever (#132).
//
// A count is what tells the difference, and only the server can give it: it is
// the one that knows how many devices a person has published from. Asking for
// key packages would answer the same question and spend one to do it - a claim
// is a delete - so the supply would be gone within the hour.
//
// Nothing is learnt from the answer that the group does not already show:
// everybody in a conversation can see everybody's leaves.
type TLMlsDevicesOf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []int64                `protobuf:"varint,1,rep,packed,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMlsDevicesOf) Reset() {
	*x = TLMlsDevicesOf{}
	mi := &file_mtproto_mls_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMlsDevicesOf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMlsDevicesOf) ProtoMessage() {}

func (x *TLMlsDevicesOf) ProtoReflect() protoreflect.Message {
	mi := &file_mtproto_mls_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMlsDevicesOf.ProtoReflect.Descriptor instead.
func (*TLMlsDevicesOf) Descriptor() ([]byte, []int) {
	return file_mtproto_mls_proto_rawDescGZIP(), []int{16}
}

func (x *TLMlsDevicesOf) GetUsers() []int64 {
	if x != nil {
		return x.Users
	}
	return nil
}

// One count per person asked about, in the order they were asked, and the name
// of every one of those devices after it.
//
// The names run as one list rather than one list per person: TL has no ragged
// vector, and the counts already say where to cut. That is the point of putting
// them in one answer - a leaf is taken out on two questions, whether a device
// is missing (the count) and which leaf is it (the names), and while those came
// from two calls they could disagree. Nobody dared act on them for anybody but
// their own account, so a leaf whose device is gone stayed for ever and every
// commit was encrypted to it (#139).
//
// A name may be empty: a device that published before key packages said which
// identity they belong to (#136) is counted and cannot be named. It is still
// one entry, so the cut stays right, and a caller that finds an empty name
// knows this person has a device it cannot account for and must not decide
// anything about their leaves.
type Mls_DeviceCounts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Counts        []int32                `protobuf:"varint,1,rep,packed,name=counts,proto3" json:"counts,omitempty"`
	Names         [][]byte               `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mls_DeviceCounts) Reset() {
	*x = Mls_DeviceCounts{}
	mi := &file_mtproto_mls_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mls_DeviceCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mls_DeviceCounts) ProtoMessage() {}

func (x *Mls_DeviceCounts) ProtoReflect() protoreflect.Message {
	mi := &file_mtproto_mls_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mls_DeviceCounts.ProtoReflect.Descriptor instead.
func (*Mls_DeviceCounts) Descriptor() ([]byte, []int) {
	return file_mtproto_mls_proto_rawDescGZIP(), []int{17}
}

func (x *Mls_DeviceCounts) GetCounts() []int32 {
	if x != nil {
		return x.Counts
	}
	return nil
}

func (x *Mls_DeviceCounts) GetNames() [][]byte {
	if x != nil {
		return x.Names
	}
	return nil
}

// A device saying it has started the conversation for a chat.
//
// Nothing decided which conversation a chat's is, so every device that wanted
// to send into one without a conversation started one of its own - and three
// people beginning a group within a minute ended in two conversations that
// cannot read each other (#135). Devices cannot settle it among themselves:
// the losers have to be told, and when everybody is offline and arrives in a
// random order there is nobody to tell them.
//
// So the first claim wins, and the answer is the same for everybody from then
// on. A device whose claim loses throws its own away and waits: it is in the
// chat, and the members of the conversation that won will see it has no leaf
// there and let it in.
type TLMlsClaimConversation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        int64                  `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	GroupId       []byte                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMlsClaimConversation) Reset() {
	*x = TLMlsClaimConversation{}
	mi := &file_mtproto_mls_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMlsClaimConversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMlsClaimConversation) ProtoMessage() {}

func (x *TLMlsClaimConversation) ProtoReflect() protoreflect.Message {
	mi := &file_mtproto_mls_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMlsClaimConversation.ProtoReflect.Descriptor instead.
func (*TLMlsClaimConversation) Descriptor() ([]byte, []int) {
	return file_mtproto_mls_proto_rawDescGZIP(), []int{18}
}

func (x *TLMlsClaimConversation) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *TLMlsClaimConversation) GetGroupId() []byte {
	if x != nil {
		return x.GroupId
	}
	return nil
}

// The conversation this chat has, which is the claimant's own when it was
// first and somebody else's when it was not.
type Mls_Conversation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        int64                  `protobuf:"varint,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	GroupId       []byte                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mls_Conversation) Reset() {
	*x = Mls_Conversation{}
	mi := &file_mtproto_mls_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mls_Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mls_Conversation) ProtoMessage() {}

func (x *Mls_Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_mtproto_mls_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mls_Conversation.ProtoReflect.Descriptor instead.
func (*Mls_Conversation) Descriptor() ([]byte, []int) {
	return file_mtproto_mls_proto_rawDescGZIP(), []int{19}
}

func (x *Mls_Conversation) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *Mls_Conversation) GetGroupId() []byte {
	if x != nil {
		return x.GroupId
	}
	return nil
}

// A device registering the way back into its own account.
//
// What arrives is not the recovery phrase: it is a one-way derivation of the
// words, made on the phone. The words are made there too and never travel,
// because a phrase signs in without a code - it is the whole account - and the
// server holding a copy of one is the server holding the account.
//
// It also decides whether an encrypted history backup means anything: the
// backup key comes from the same words by a different derivation, so a server
// that never sees the words cannot read the backup either.
type TLMlsSetRecoverySecret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLMlsSetRecoverySecret) Reset() {
	*x = TLMlsSetRecoverySecret{}
	mi := &file_mtproto_mls_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLMlsSetRecoverySecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLMlsSetRecoverySecret) ProtoMessage() {}

func (x *TLMlsSetRecoverySecret) ProtoReflect() protoreflect.Message {
	mi := &file_mtproto_mls_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLMlsSetRecoverySecret.ProtoReflect.Descriptor instead.
func (*TLMlsSetRecoverySecret) Descriptor() ([]byte, []int) {
	return file_mtproto_mls_proto_rawDescGZIP(), []int{20}
}

func (x *TLMlsSetRecoverySecret) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

var File_mtproto_mls_proto protoreflect.FileDescriptor

const file_mtproto_mls_proto_rawDesc = "" +
	"\n" +
	"\x11mtproto/mls.proto\x12\amtproto\"s\n" +
	"\x19TL_mls_publishKeyPackages\x12!\n" +
	"\fkey_packages\x18\x01 \x03(\fR\vkeyPackages\x12\x1f\n" +
	"\vlast_resort\x18\x02 \x01(\fR\n" +
	"lastResort\x12\x12\n" +
	"\x04name\x18\x03 \x01(\fR\x04name\"\x86\x01\n" +
	"\x11mls_PublishResult\x12\x14\n" +
	"\x05added\x18\x01 \x01(\x05R\x05added\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\x05R\tavailable\x12#\n" +
	"\rshould_refill\x18\x03 \x01(\bR\fshouldRefill\x12\x18\n" +
	"\adevices\x18\x04 \x01(\x05R\adevices\"2\n" +
	"\x17TL_mls_claimKeyPackages\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"-\n" +
	"\x0fmls_KeyPackages\x12\x1a\n" +
	"\bpackages\x18\x01 \x03(\fR\bpackages\"`\n" +
	"\x12TL_mls_sendWelcome\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\awelcome\x18\x02 \x01(\fR\awelcome\x12\x17\n" +
	"\apeer_id\x18\x03 \x01(\x03R\x06peerId\"\x14\n" +
	"\x12TL_mls_getWelcomes\"\x18\n" +
	"\x06mls_Ok\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"i\n" +
	"\vmls_Welcome\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\afrom_id\x18\x02 \x01(\x03R\x06fromId\x12\x18\n" +
	"\awelcome\x18\x03 \x01(\fR\awelcome\x12\x17\n" +
	"\apeer_id\x18\x04 \x01(\x03R\x06peerId\"@\n" +
	"\fmls_Welcomes\x120\n" +
	"\bwelcomes\x18\x01 \x03(\v2\x14.mtproto.mls_WelcomeR\bwelcomes\"*\n" +
	"\x16TL_mls_confirmWelcomes\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"v\n" +
	"\x11TL_mls_sendCommit\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\fR\agroupId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x12\x18\n" +
	"\amembers\x18\x03 \x03(\x03R\amembers\x12\x16\n" +
	"\x06commit\x18\x04 \x01(\fR\x06commit\"D\n" +
	"\x10mls_CommitResult\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\"\x13\n" +
	"\x11TL_mls_getCommits\"~\n" +
	"\n" +
	"mls_Commit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\afrom_id\x18\x02 \x01(\x03R\x06fromId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\fR\agroupId\x12\x14\n" +
	"\x05epoch\x18\x04 \x01(\x03R\x05epoch\x12\x16\n" +
	"\x06commit\x18\x05 \x01(\fR\x06commit\"<\n" +
	"\vmls_Commits\x12-\n" +
	"\acommits\x18\x01 \x03(\v2\x13.mtproto.mls_CommitR\acommits\")\n" +
	"\x15TL_mls_confirmCommits\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"(\n" +
	"\x10TL_mls_devicesOf\x12\x14\n" +
	"\x05users\x18\x01 \x03(\x03R\x05users\"@\n" +
	"\x10mls_DeviceCounts\x12\x16\n" +
	"\x06counts\x18\x01 \x03(\x05R\x06counts\x12\x14\n" +
	"\x05names\x18\x02 \x03(\fR\x05names\"N\n" +
	"\x18TL_mls_claimConversation\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\x03R\x06peerId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\fR\agroupId\"F\n" +
	"\x10mls_Conversation\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\x03R\x06peerId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\fR\agroupId\"2\n" +
	"\x18TL_mls_setRecoverySecret\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret2\xdc\x06\n" +
	"\x06RPCMls\x12Z\n" +
	"\x16mls_publishKeyPackages\x12\".mtproto.TL_mls_publishKeyPackages\x1a\x1a.mtproto.mls_PublishResult\"\x00\x12T\n" +
	"\x14mls_claimKeyPackages\x12 .mtproto.TL_mls_claimKeyPackages\x1a\x18.mtproto.mls_KeyPackages\"\x00\x12A\n" +
	"\x0fmls_sendWelcome\x12\x1b.mtproto.TL_mls_sendWelcome\x1a\x0f.mtproto.mls_Ok\"\x00\x12G\n" +
	"\x0fmls_getWelcomes\x12\x1b.mtproto.TL_mls_getWelcomes\x1a\x15.mtproto.mls_Welcomes\"\x00\x12I\n" +
	"\x13mls_confirmWelcomes\x12\x1f.mtproto.TL_mls_confirmWelcomes\x1a\x0f.mtproto.mls_Ok\"\x00\x12M\n" +
	"\x15mls_setRecoverySecret\x12!.mtproto.TL_mls_setRecoverySecret\x1a\x0f.mtproto.mls_Ok\"\x00\x12I\n" +
	"\x0emls_sendCommit\x12\x1a.mtproto.TL_mls_sendCommit\x1a\x19.mtproto.mls_CommitResult\"\x00\x12D\n" +
	"\x0emls_getCommits\x12\x1a.mtproto.TL_mls_getCommits\x1a\x14.mtproto.mls_Commits\"\x00\x12G\n" +
	"\x12mls_confirmCommits\x12\x1e.mtproto.TL_mls_confirmCommits\x1a\x0f.mtproto.mls_Ok\"\x00\x12G\n" +
	"\rmls_devicesOf\x12\x19.mtproto.TL_mls_devicesOf\x1a\x19.mtproto.mls_DeviceCounts\"\x00\x12W\n" +
	"\x15mls_claimConversation\x12!.mtproto.TL_mls_claimConversation\x1a\x19.mtproto.mls_Conversation\"\x00B#Z!github.com/teamgram/proto/mtprotob\x06proto3"

var (
	file_mtproto_mls_proto_rawDescOnce sync.Once
	file_mtproto_mls_proto_rawDescData []byte
)

func file_mtproto_mls_proto_rawDescGZIP() []byte {
	file_mtproto_mls_proto_rawDescOnce.Do(func() {
		file_mtproto_mls_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mtproto_mls_proto_rawDesc), len(file_mtproto_mls_proto_rawDesc)))
	})
	return file_mtproto_mls_proto_rawDescData
}

var file_mtproto_mls_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_mtproto_mls_proto_goTypes = []any{
	(*TLMlsPublishKeyPackages)(nil), // 0: mtproto.TL_mls_publishKeyPackages
	(*Mls_PublishResult)(nil),       // 1: mtproto.mls_PublishResult
	(*TLMlsClaimKeyPackages)(nil),   // 2: mtproto.TL_mls_claimKeyPackages
	(*Mls_KeyPackages)(nil),         // 3: mtproto.mls_KeyPackages
	(*TLMlsSendWelcome)(nil),        // 4: mtproto.TL_mls_sendWelcome
	(*TLMlsGetWelcomes)(nil),        // 5: mtproto.TL_mls_getWelcomes
	(*Mls_Ok)(nil),                  // 6: mtproto.mls_Ok
	(*Mls_Welcome)(nil),             // 7: mtproto.mls_Welcome
	(*Mls_Welcomes)(nil),            // 8: mtproto.mls_Welcomes
	(*TLMlsConfirmWelcomes)(nil),    // 9: mtproto.TL_mls_confirmWelcomes
	(*TLMlsSendCommit)(nil),         // 10: mtproto.TL_mls_sendCommit
	(*Mls_CommitResult)(nil),        // 11: mtproto.mls_CommitResult
	(*TLMlsGetCommits)(nil),         // 12: mtproto.TL_mls_getCommits
	(*Mls_Commit)(nil),              // 13: mtproto.mls_Commit
	(*Mls_Commits)(nil),             // 14: mtproto.mls_Commits
	(*TLMlsConfirmCommits)(nil),     // 15: mtproto.TL_mls_confirmCommits
	(*TLMlsDevicesOf)(nil),          // 16: mtproto.TL_mls_devicesOf
	(*Mls_DeviceCounts)(nil),        // 17: mtproto.mls_DeviceCounts
	(*TLMlsClaimConversation)(nil),  // 18: mtproto.TL_mls_claimConversation
	(*Mls_Conversation)(nil),        // 19: mtproto.mls_Conversation
	(*TLMlsSetRecoverySecret)(nil),  // 20: mtproto.TL_mls_setRecoverySecret
}
var file_mtproto_mls_proto_depIdxs = []int32{
	7,  // 0: mtproto.mls_Welcomes.welcomes:type_name -> mtproto.mls_Welcome
	13, // 1: mtproto.mls_Commits.commits:type_name -> mtproto.mls_Commit
	0,  // 2: mtproto.RPCMls.mls_publishKeyPackages:input_type -> mtproto.TL_mls_publishKeyPackages
	2,  // 3: mtproto.RPCMls.mls_claimKeyPackages:input_type -> mtproto.TL_mls_claimKeyPackages
	4,  // 4: mtproto.RPCMls.mls_sendWelcome:input_type -> mtproto.TL_mls_sendWelcome
	5,  // 5: mtproto.RPCMls.mls_getWelcomes:input_type -> mtproto.TL_mls_getWelcomes
	9,  // 6: mtproto.RPCMls.mls_confirmWelcomes:input_type -> mtproto.TL_mls_confirmWelcomes
	20, // 7: mtproto.RPCMls.mls_setRecoverySecret:input_type -> mtproto.TL_mls_setRecoverySecret
	10, // 8: mtproto.RPCMls.mls_sendCommit:input_type -> mtproto.TL_mls_sendCommit
	12, // 9: mtproto.RPCMls.mls_getCommits:input_type -> mtproto.TL_mls_getCommits
	15, // 10: mtproto.RPCMls.mls_confirmCommits:input_type -> mtproto.TL_mls_confirmCommits
	16, // 11: mtproto.RPCMls.mls_devicesOf:input_type -> mtproto.TL_mls_devicesOf
	18, // 12: mtproto.RPCMls.mls_claimConversation:input_type -> mtproto.TL_mls_claimConversation
	1,  // 13: mtproto.RPCMls.mls_publishKeyPackages:output_type -> mtproto.mls_PublishResult
	3,  // 14: mtproto.RPCMls.mls_claimKeyPackages:output_type -> mtproto.mls_KeyPackages
	6,  // 15: mtproto.RPCMls.mls_sendWelcome:output_type -> mtproto.mls_Ok
	8,  // 16: mtproto.RPCMls.mls_getWelcomes:output_type -> mtproto.mls_Welcomes
	6,  // 17: mtproto.RPCMls.mls_confirmWelcomes:output_type -> mtproto.mls_Ok
	6,  // 18: mtproto.RPCMls.mls_setRecoverySecret:output_type -> mtproto.mls_Ok
	11, // 19: mtproto.RPCMls.mls_sendCommit:output_type -> mtproto.mls_CommitResult
	14, // 20: mtproto.RPCMls.mls_getCommits:output_type -> mtproto.mls_Commits
	6,  // 21: mtproto.RPCMls.mls_confirmCommits:output_type -> mtproto.mls_Ok
	17, // 22: mtproto.RPCMls.mls_devicesOf:output_type -> mtproto.mls_DeviceCounts
	19, // 23: mtproto.RPCMls.mls_claimConversation:output_type -> mtproto.mls_Conversation
	13, // [13:24] is the sub-list for method output_type
	2,  // [2:13] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_mtproto_mls_proto_init() }
func file_mtproto_mls_proto_init() {
	if File_mtproto_mls_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mtproto_mls_proto_rawDesc), len(file_mtproto_mls_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mtproto_mls_proto_goTypes,
		DependencyIndexes: file_mtproto_mls_proto_depIdxs,
		MessageInfos:      file_mtproto_mls_proto_msgTypes,
	}.Build()
	File_mtproto_mls_proto = out.File
	file_mtproto_mls_proto_goTypes = nil
	file_mtproto_mls_proto_depIdxs = nil
}
