// Our own methods, for end-to-end encryption on MLS (2bytes #36).
//
// Kept in a file of its own rather than added to the generated schema, so that
// regenerating that schema from upstream cannot quietly drop them, and so that
// updating this module has exactly one file to carry across.
//
// The wire encoding these types use towards the phone is written by hand in
// mls.go - MTProto, not protobuf. This file exists because the services inside
// the server talk protobuf to each other, and a type that is not a protobuf
// message cannot make that hop.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: mtproto/mls.proto

package mtproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RPCMls_MlsPublishKeyPackages_FullMethodName = "/mtproto.RPCMls/mls_publishKeyPackages"
	RPCMls_MlsClaimKeyPackages_FullMethodName   = "/mtproto.RPCMls/mls_claimKeyPackages"
	RPCMls_MlsSendWelcome_FullMethodName        = "/mtproto.RPCMls/mls_sendWelcome"
	RPCMls_MlsGetWelcomes_FullMethodName        = "/mtproto.RPCMls/mls_getWelcomes"
	RPCMls_MlsConfirmWelcomes_FullMethodName    = "/mtproto.RPCMls/mls_confirmWelcomes"
	RPCMls_MlsSetRecoverySecret_FullMethodName  = "/mtproto.RPCMls/mls_setRecoverySecret"
	RPCMls_MlsSendCommit_FullMethodName         = "/mtproto.RPCMls/mls_sendCommit"
	RPCMls_MlsGetCommits_FullMethodName         = "/mtproto.RPCMls/mls_getCommits"
	RPCMls_MlsConfirmCommits_FullMethodName     = "/mtproto.RPCMls/mls_confirmCommits"
)

// RPCMlsClient is the client API for RPCMls service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RPCMlsClient interface {
	MlsPublishKeyPackages(ctx context.Context, in *TLMlsPublishKeyPackages, opts ...grpc.CallOption) (*Mls_PublishResult, error)
	MlsClaimKeyPackages(ctx context.Context, in *TLMlsClaimKeyPackages, opts ...grpc.CallOption) (*Mls_KeyPackages, error)
	MlsSendWelcome(ctx context.Context, in *TLMlsSendWelcome, opts ...grpc.CallOption) (*Mls_Ok, error)
	MlsGetWelcomes(ctx context.Context, in *TLMlsGetWelcomes, opts ...grpc.CallOption) (*Mls_Welcomes, error)
	MlsConfirmWelcomes(ctx context.Context, in *TLMlsConfirmWelcomes, opts ...grpc.CallOption) (*Mls_Ok, error)
	MlsSetRecoverySecret(ctx context.Context, in *TLMlsSetRecoverySecret, opts ...grpc.CallOption) (*Mls_Ok, error)
	MlsSendCommit(ctx context.Context, in *TLMlsSendCommit, opts ...grpc.CallOption) (*Mls_CommitResult, error)
	MlsGetCommits(ctx context.Context, in *TLMlsGetCommits, opts ...grpc.CallOption) (*Mls_Commits, error)
	MlsConfirmCommits(ctx context.Context, in *TLMlsConfirmCommits, opts ...grpc.CallOption) (*Mls_Ok, error)
}

type rPCMlsClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCMlsClient(cc grpc.ClientConnInterface) RPCMlsClient {
	return &rPCMlsClient{cc}
}

func (c *rPCMlsClient) MlsPublishKeyPackages(ctx context.Context, in *TLMlsPublishKeyPackages, opts ...grpc.CallOption) (*Mls_PublishResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Mls_PublishResult)
	err := c.cc.Invoke(ctx, RPCMls_MlsPublishKeyPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCMlsClient) MlsClaimKeyPackages(ctx context.Context, in *TLMlsClaimKeyPackages, opts ...grpc.CallOption) (*Mls_KeyPackages, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Mls_KeyPackages)
	err := c.cc.Invoke(ctx, RPCMls_MlsClaimKeyPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCMlsClient) MlsSendWelcome(ctx context.Context, in *TLMlsSendWelcome, opts ...grpc.CallOption) (*Mls_Ok, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Mls_Ok)
	err := c.cc.Invoke(ctx, RPCMls_MlsSendWelcome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCMlsClient) MlsGetWelcomes(ctx context.Context, in *TLMlsGetWelcomes, opts ...grpc.CallOption) (*Mls_Welcomes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Mls_Welcomes)
	err := c.cc.Invoke(ctx, RPCMls_MlsGetWelcomes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCMlsClient) MlsConfirmWelcomes(ctx context.Context, in *TLMlsConfirmWelcomes, opts ...grpc.CallOption) (*Mls_Ok, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Mls_Ok)
	err := c.cc.Invoke(ctx, RPCMls_MlsConfirmWelcomes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCMlsClient) MlsSetRecoverySecret(ctx context.Context, in *TLMlsSetRecoverySecret, opts ...grpc.CallOption) (*Mls_Ok, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Mls_Ok)
	err := c.cc.Invoke(ctx, RPCMls_MlsSetRecoverySecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCMlsClient) MlsSendCommit(ctx context.Context, in *TLMlsSendCommit, opts ...grpc.CallOption) (*Mls_CommitResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Mls_CommitResult)
	err := c.cc.Invoke(ctx, RPCMls_MlsSendCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCMlsClient) MlsGetCommits(ctx context.Context, in *TLMlsGetCommits, opts ...grpc.CallOption) (*Mls_Commits, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Mls_Commits)
	err := c.cc.Invoke(ctx, RPCMls_MlsGetCommits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCMlsClient) MlsConfirmCommits(ctx context.Context, in *TLMlsConfirmCommits, opts ...grpc.CallOption) (*Mls_Ok, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Mls_Ok)
	err := c.cc.Invoke(ctx, RPCMls_MlsConfirmCommits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCMlsServer is the server API for RPCMls service.
// All implementations must embed UnimplementedRPCMlsServer
// for forward compatibility.
type RPCMlsServer interface {
	MlsPublishKeyPackages(context.Context, *TLMlsPublishKeyPackages) (*Mls_PublishResult, error)
	MlsClaimKeyPackages(context.Context, *TLMlsClaimKeyPackages) (*Mls_KeyPackages, error)
	MlsSendWelcome(context.Context, *TLMlsSendWelcome) (*Mls_Ok, error)
	MlsGetWelcomes(context.Context, *TLMlsGetWelcomes) (*Mls_Welcomes, error)
	MlsConfirmWelcomes(context.Context, *TLMlsConfirmWelcomes) (*Mls_Ok, error)
	MlsSetRecoverySecret(context.Context, *TLMlsSetRecoverySecret) (*Mls_Ok, error)
	MlsSendCommit(context.Context, *TLMlsSendCommit) (*Mls_CommitResult, error)
	MlsGetCommits(context.Context, *TLMlsGetCommits) (*Mls_Commits, error)
	MlsConfirmCommits(context.Context, *TLMlsConfirmCommits) (*Mls_Ok, error)
	mustEmbedUnimplementedRPCMlsServer()
}

// UnimplementedRPCMlsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRPCMlsServer struct{}

func (UnimplementedRPCMlsServer) MlsPublishKeyPackages(context.Context, *TLMlsPublishKeyPackages) (*Mls_PublishResult, error) {
	return nil, status.Error(codes.Unimplemented, "method MlsPublishKeyPackages not implemented")
}
func (UnimplementedRPCMlsServer) MlsClaimKeyPackages(context.Context, *TLMlsClaimKeyPackages) (*Mls_KeyPackages, error) {
	return nil, status.Error(codes.Unimplemented, "method MlsClaimKeyPackages not implemented")
}
func (UnimplementedRPCMlsServer) MlsSendWelcome(context.Context, *TLMlsSendWelcome) (*Mls_Ok, error) {
	return nil, status.Error(codes.Unimplemented, "method MlsSendWelcome not implemented")
}
func (UnimplementedRPCMlsServer) MlsGetWelcomes(context.Context, *TLMlsGetWelcomes) (*Mls_Welcomes, error) {
	return nil, status.Error(codes.Unimplemented, "method MlsGetWelcomes not implemented")
}
func (UnimplementedRPCMlsServer) MlsConfirmWelcomes(context.Context, *TLMlsConfirmWelcomes) (*Mls_Ok, error) {
	return nil, status.Error(codes.Unimplemented, "method MlsConfirmWelcomes not implemented")
}
func (UnimplementedRPCMlsServer) MlsSetRecoverySecret(context.Context, *TLMlsSetRecoverySecret) (*Mls_Ok, error) {
	return nil, status.Error(codes.Unimplemented, "method MlsSetRecoverySecret not implemented")
}
func (UnimplementedRPCMlsServer) MlsSendCommit(context.Context, *TLMlsSendCommit) (*Mls_CommitResult, error) {
	return nil, status.Error(codes.Unimplemented, "method MlsSendCommit not implemented")
}
func (UnimplementedRPCMlsServer) MlsGetCommits(context.Context, *TLMlsGetCommits) (*Mls_Commits, error) {
	return nil, status.Error(codes.Unimplemented, "method MlsGetCommits not implemented")
}
func (UnimplementedRPCMlsServer) MlsConfirmCommits(context.Context, *TLMlsConfirmCommits) (*Mls_Ok, error) {
	return nil, status.Error(codes.Unimplemented, "method MlsConfirmCommits not implemented")
}
func (UnimplementedRPCMlsServer) mustEmbedUnimplementedRPCMlsServer() {}
func (UnimplementedRPCMlsServer) testEmbeddedByValue()                {}

// UnsafeRPCMlsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCMlsServer will
// result in compilation errors.
type UnsafeRPCMlsServer interface {
	mustEmbedUnimplementedRPCMlsServer()
}

func RegisterRPCMlsServer(s grpc.ServiceRegistrar, srv RPCMlsServer) {
	// If the following call panics, it indicates UnimplementedRPCMlsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RPCMls_ServiceDesc, srv)
}

func _RPCMls_MlsPublishKeyPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLMlsPublishKeyPackages)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCMlsServer).MlsPublishKeyPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCMls_MlsPublishKeyPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCMlsServer).MlsPublishKeyPackages(ctx, req.(*TLMlsPublishKeyPackages))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCMls_MlsClaimKeyPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLMlsClaimKeyPackages)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCMlsServer).MlsClaimKeyPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCMls_MlsClaimKeyPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCMlsServer).MlsClaimKeyPackages(ctx, req.(*TLMlsClaimKeyPackages))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCMls_MlsSendWelcome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLMlsSendWelcome)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCMlsServer).MlsSendWelcome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCMls_MlsSendWelcome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCMlsServer).MlsSendWelcome(ctx, req.(*TLMlsSendWelcome))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCMls_MlsGetWelcomes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLMlsGetWelcomes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCMlsServer).MlsGetWelcomes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCMls_MlsGetWelcomes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCMlsServer).MlsGetWelcomes(ctx, req.(*TLMlsGetWelcomes))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCMls_MlsConfirmWelcomes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLMlsConfirmWelcomes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCMlsServer).MlsConfirmWelcomes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCMls_MlsConfirmWelcomes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCMlsServer).MlsConfirmWelcomes(ctx, req.(*TLMlsConfirmWelcomes))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCMls_MlsSetRecoverySecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLMlsSetRecoverySecret)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCMlsServer).MlsSetRecoverySecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCMls_MlsSetRecoverySecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCMlsServer).MlsSetRecoverySecret(ctx, req.(*TLMlsSetRecoverySecret))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCMls_MlsSendCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLMlsSendCommit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCMlsServer).MlsSendCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCMls_MlsSendCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCMlsServer).MlsSendCommit(ctx, req.(*TLMlsSendCommit))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCMls_MlsGetCommits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLMlsGetCommits)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCMlsServer).MlsGetCommits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCMls_MlsGetCommits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCMlsServer).MlsGetCommits(ctx, req.(*TLMlsGetCommits))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCMls_MlsConfirmCommits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLMlsConfirmCommits)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCMlsServer).MlsConfirmCommits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCMls_MlsConfirmCommits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCMlsServer).MlsConfirmCommits(ctx, req.(*TLMlsConfirmCommits))
	}
	return interceptor(ctx, in, info, handler)
}

// RPCMls_ServiceDesc is the grpc.ServiceDesc for RPCMls service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPCMls_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mtproto.RPCMls",
	HandlerType: (*RPCMlsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "mls_publishKeyPackages",
			Handler:    _RPCMls_MlsPublishKeyPackages_Handler,
		},
		{
			MethodName: "mls_claimKeyPackages",
			Handler:    _RPCMls_MlsClaimKeyPackages_Handler,
		},
		{
			MethodName: "mls_sendWelcome",
			Handler:    _RPCMls_MlsSendWelcome_Handler,
		},
		{
			MethodName: "mls_getWelcomes",
			Handler:    _RPCMls_MlsGetWelcomes_Handler,
		},
		{
			MethodName: "mls_confirmWelcomes",
			Handler:    _RPCMls_MlsConfirmWelcomes_Handler,
		},
		{
			MethodName: "mls_setRecoverySecret",
			Handler:    _RPCMls_MlsSetRecoverySecret_Handler,
		},
		{
			MethodName: "mls_sendCommit",
			Handler:    _RPCMls_MlsSendCommit_Handler,
		},
		{
			MethodName: "mls_getCommits",
			Handler:    _RPCMls_MlsGetCommits_Handler,
		},
		{
			MethodName: "mls_confirmCommits",
			Handler:    _RPCMls_MlsConfirmCommits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mtproto/mls.proto",
}
