// Our own methods, for end-to-end encryption on MLS (2bytes #36).
//
// Kept in a file of its own rather than added to the generated schema, so that
// regenerating that schema from upstream cannot quietly drop them, and so that
// updating this module has exactly one file to carry across.
//
// The wire encoding these types use towards the phone is written by hand in
// mls.go - MTProto, not protobuf. This file exists because the services inside
// the server talk protobuf to each other, and a type that is not a protobuf
// message cannot make that hop.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: mls.proto

package mtproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RPCMls_MlsPublishKeyPackages_FullMethodName = "/mtproto.RPCMls/mls_publishKeyPackages"
	RPCMls_MlsClaimKeyPackages_FullMethodName   = "/mtproto.RPCMls/mls_claimKeyPackages"
)

// RPCMlsClient is the client API for RPCMls service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RPCMlsClient interface {
	MlsPublishKeyPackages(ctx context.Context, in *TLMlsPublishKeyPackages, opts ...grpc.CallOption) (*Mls_PublishResult, error)
	MlsClaimKeyPackages(ctx context.Context, in *TLMlsClaimKeyPackages, opts ...grpc.CallOption) (*Mls_KeyPackages, error)
}

type rPCMlsClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCMlsClient(cc grpc.ClientConnInterface) RPCMlsClient {
	return &rPCMlsClient{cc}
}

func (c *rPCMlsClient) MlsPublishKeyPackages(ctx context.Context, in *TLMlsPublishKeyPackages, opts ...grpc.CallOption) (*Mls_PublishResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Mls_PublishResult)
	err := c.cc.Invoke(ctx, RPCMls_MlsPublishKeyPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCMlsClient) MlsClaimKeyPackages(ctx context.Context, in *TLMlsClaimKeyPackages, opts ...grpc.CallOption) (*Mls_KeyPackages, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Mls_KeyPackages)
	err := c.cc.Invoke(ctx, RPCMls_MlsClaimKeyPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCMlsServer is the server API for RPCMls service.
// All implementations must embed UnimplementedRPCMlsServer
// for forward compatibility.
type RPCMlsServer interface {
	MlsPublishKeyPackages(context.Context, *TLMlsPublishKeyPackages) (*Mls_PublishResult, error)
	MlsClaimKeyPackages(context.Context, *TLMlsClaimKeyPackages) (*Mls_KeyPackages, error)
	mustEmbedUnimplementedRPCMlsServer()
}

// UnimplementedRPCMlsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRPCMlsServer struct{}

func (UnimplementedRPCMlsServer) MlsPublishKeyPackages(context.Context, *TLMlsPublishKeyPackages) (*Mls_PublishResult, error) {
	return nil, status.Error(codes.Unimplemented, "method MlsPublishKeyPackages not implemented")
}
func (UnimplementedRPCMlsServer) MlsClaimKeyPackages(context.Context, *TLMlsClaimKeyPackages) (*Mls_KeyPackages, error) {
	return nil, status.Error(codes.Unimplemented, "method MlsClaimKeyPackages not implemented")
}
func (UnimplementedRPCMlsServer) mustEmbedUnimplementedRPCMlsServer() {}
func (UnimplementedRPCMlsServer) testEmbeddedByValue()                {}

// UnsafeRPCMlsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RPCMlsServer will
// result in compilation errors.
type UnsafeRPCMlsServer interface {
	mustEmbedUnimplementedRPCMlsServer()
}

func RegisterRPCMlsServer(s grpc.ServiceRegistrar, srv RPCMlsServer) {
	// If the following call panics, it indicates UnimplementedRPCMlsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RPCMls_ServiceDesc, srv)
}

func _RPCMls_MlsPublishKeyPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLMlsPublishKeyPackages)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCMlsServer).MlsPublishKeyPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCMls_MlsPublishKeyPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCMlsServer).MlsPublishKeyPackages(ctx, req.(*TLMlsPublishKeyPackages))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCMls_MlsClaimKeyPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TLMlsClaimKeyPackages)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCMlsServer).MlsClaimKeyPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RPCMls_MlsClaimKeyPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCMlsServer).MlsClaimKeyPackages(ctx, req.(*TLMlsClaimKeyPackages))
	}
	return interceptor(ctx, in, info, handler)
}

// RPCMls_ServiceDesc is the grpc.ServiceDesc for RPCMls service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RPCMls_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mtproto.RPCMls",
	HandlerType: (*RPCMlsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "mls_publishKeyPackages",
			Handler:    _RPCMls_MlsPublishKeyPackages_Handler,
		},
		{
			MethodName: "mls_claimKeyPackages",
			Handler:    _RPCMls_MlsClaimKeyPackages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mls.proto",
}
